### ISSUE TITLE
NullPointerException received upon user login.

### ISSUE THREAD

**Issue by witchyface** [Pixelmon-Development/BetterDexRewards#29]
Hey Daniel,

I'm sure this has something to do with my config setup as honestly the whole X and Y value thing I'm not confident I've gotten correct. But I wonder if you could provide some insight as to where I'm going wrong.

Error received as shown below.

Cheers,

Jimmy/Rain

`[10:27:52] [Server thread/INFO] [minecraft/PlayerList]: UseRainDance[/127.0.0.1:21245] logged in with entity id 60 at (227.5, 77.0, 10.5)
[10:27:52] [envyware_concurrency_2/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: java.lang.NullPointerException
[10:27:52] [envyware_concurrency_2/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:     at com.envyful.better.dex.rewards.forge.player.DexRewardsAttribute.load(DexRewardsAttribute.java:70)
[10:27:52] [envyware_concurrency_2/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:     at com.envyful.better.dex.rewards.shade.envy.api.forge.player.ForgePlayerManager$PlayerListener.lambda$onPlayerJoin$0(ForgePlayerManager.java:118)
[10:27:52] [envyware_concurrency_2/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[10:27:52] [envyware_concurrency_2/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[10:27:52] [envyware_concurrency_2/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:     at java.base/java.lang.Thread.run(Thread.java:829)`

**Comment by danorris709** [comment]
Your database isn't connecting for some reason it seems

**Comment by danorris709** [comment]
Closing because this is a config issue
